### PR TITLE
Migrate to AndroidX & Update dependencies

### PR DESCRIPTION
**Pull request by blundell**
Migrates from the support library to AndroidX
Updates gradle from v4 to v5
Bumps the compile sdk to 29 alongside the gradle plugin & build tools.

Supercedes #465
Relates to #438
Fixed AndroidX issue mentioned in #444

### CODE REVIEW

**Comment by blundell** [comment]
```
* What went wrong:
A problem occurred configuring project ':library'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;29.0.2 Android SDK Build-Tools 29.0.2
     platforms;android-29 Android SDK Platform 29
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
```

*Someone with admin needs to accept the Android SDK 29 license*

**Comment by iainmcgin** [comment]
Should we do this on master, or in a separate branch? I suppose at this point AndroidX should be stable and pervasive enough that we can release a new major version with this in use and leave the 0.x tree for the pre-AndroidX days.

**Comment by hnljp** [comment]
Hello

It should be done on master, the support libraries have been deprecated by google for a while now.

Best regards,
Henning Lund


Med venlig hilsen
Henning Nielsen Lund

Softwareudvikler, Native Apps Team



Jyllands-Posten | JP Medier

Grøndalsvej 3 8260 Viby J

________________________________

**Comment by karensg** [comment]
@blundell Thanks for your PR! Any idea when we can get this merged?

**Comment by victoruriarte** [comment]
I have the original Appauth-Android project and I just downloaded this with androidx compatibility. I have copied the original json data to this project but it doesn't login to keycloak, it always returns error. Any compatibility issue?

**Comment by jajmo** [comment]
@victoruriarte I use this branch locally in one of my projects with Keycloak without error. What errors are you getting?

**Comment by nshroff-ptc** [comment]
I was trying to update to AndroidX but when I do that I encounter below issue:

Caused by: org.gradle.api.InvalidUserDataException: Cannot change strategy of configuration ':app:compile' after it has been resolved.

Did anyone face this issue before? or do we have any repo where AppAuth is already using AndroidX libraries?

**Comment by CurtesMalteser** [comment]
There's any plan to merge these changes?
Or even update the project any time soon?

**Comment by nshroff-ptc** [comment]
I have the same query. Do we plan to merge this soon?

**Comment by CurtesMalteser** [comment]
In fact if there's the need for help with test something and eventually contribute with some wrok, let me know.
I really would like to see this project updated.

**Comment by jajmo** [comment]
@iainmcgin any plans on merging this in?

**Comment by CurtesMalteser** [comment]
I see that that the problem isn't just update to AndroidX. The library is very deprecated. Starting with usage of AsyncTaskManager to assertJ Android from square that isn't maintained.

**Comment by iainmcgin** [comment]
I am checking with @blundell whether he has signed the OpenID CLA; until I have that I can't merge their changes.

**Comment by CurtesMalteser** [comment]
Thank you @iainmcgin. Good news.
By deprecated I mean that AsyncTask as well as AsyncTaskLoader have been deprecated.
These were replaced by Kotlin Coroutines.
If the idea is to keep this project alive there's a lot of work to be done to recover it.
Maybe openID needs some help.

**Comment by CurtesMalteser** [comment]
@iainmcgin there's also an issue when moving with Android Studio 4. There are changes on new gradle plugin. Maybe you can help me solve it.

**Comment by iainmcgin** [comment]
@blundell has assured me that he signed the CLA and while it his name hasn't appeared on the list yet I don't want to delay this further, so I'll merge now.

**Comment by nshroff-ptc** [comment]
@iainmcgin Thanks for merging this code. When can we expect a new .aar file to use?

**Comment by iainmcgin** [comment]
You should be able to use jitpack until I cut a new tagged release:

https://jitpack.io/#openid/AppAuth-Android/27b62d5da9

**Comment by nshroff-ptc** [comment]
Got it. Thanks @iainmcgin

**Review by AbuIman585 — COMMENTED** [review]
**Test**

**Comment by cumcum8197** [comment]
eed3eef84099348f9b507d21a73ed8279da9a112

**Pull request merged**
