### PR TITLE
Fix typo in AuthorizationResponse.

### PR DESCRIPTION
**Pull request by rebeckag**
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/43)

### CODE REVIEW

**Comment by iainmcgin** [comment]
We'll need to get you to sign the contributor agreement before I can accept any of these pull requests - I'm waiting for information from @WilliamDenniss on where this is and where you need to submit it to. Hopefully he'll back to us on this soon. For now, I'll review the changes but hold back on submitting them until the contributor agreement stuff is resolved.

**Comment by iainmcgin** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/43#-:-KEBslYZGHLuaDrJ7IL9:1417088721)*

**Comment by rebeckag** [comment]
Sounds good, just let me know :)

**Comment by WilliamDenniss** [comment]
Hi @rebeckag, thank you for wanting to contributing to AppAuth, we'd be delighted if you joined the project!

I've drafted the contributing instructions here: https://github.com/WilliamDenniss/AppAuth-Android/blob/master/CONTRIBUTING.md

Once the OpenID Foundation gets your agreements (both of them), we'll add you to the CONTRIBUTORS list and can merge your pull request :)  I'm sorry that one of the agreements is paper-only currently, the Foundation is setting up an electronic signing version, but it's not yet ready. Hope it's not too inconvenient.

**Pull request merged**
