### PR TITLE
Add example of dynamic client registration in README.

### PR DESCRIPTION
**Pull request by rebeckag**
Should not be merged until a new version is released (where the dynamic client registration is included).

This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/66)

### CODE REVIEW

**Comment by iainmcgin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 193 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/66#-KGmzzYqoGV4C_BEEAXg:-KGmzzYrT9ajIBpOa4Hw:-249730213) ([raw file](https://github.com/openid/appauth-android/blob/a0a7cb6343712348939c70d4b3aabad85434d139/README.md#L193)):*
synchronous -> asynchronous

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/66)*

**Comment by tikurahul** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/66#-:-KGnChZuG-VzW1ktkRbE:1417088721)*

**Comment by rebeckag** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[README.md, line 193 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/66#-KGmzzYqoGV4C_BEEAXg:-KGoqBTPilz817Wxj6sV:-730803333) ([raw file](https://github.com/openid/appauth-android/blob/a0a7cb6343712348939c70d4b3aabad85434d139/README.md#L193)):*
I was thinking of the actual http request, which is synchronous (as compared to the auth req, asynchronous since the response gets back through the redirect).
But since this request is deferred to an AsyncTask, 'asynchronous' makes more sense if not expanding on the above distinction.

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/66)*

**Comment by iainmcgin** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[README.md, line 193 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/66#-KGmzzYqoGV4C_BEEAXg:-KGtBj6b4IjTyQIO1rOt:1491160529) ([raw file](https://github.com/openid/appauth-android/blob/a0a7cb6343712348939c70d4b3aabad85434d139/README.md#L193)):*
Sure; from the library user's perspective, it's an asynchronous call as the result is delivered via callback.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/66#-:-KGtBr9BAP1oVvnAMiEL:980077423)*

**Pull request merged**
