### PR TITLE
Amend copyright headers to reflect plurality of authors

### PR DESCRIPTION
**Pull request by iainmcgin**
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/47)

### CODE REVIEW

**Comment by iainmcgin** [comment]
+@williamdenniss for review

---

Review status: 0 of 58 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/47#-:-KFuEnRLmlYRobGUNigi:-1826320048)*

**Comment by WilliamDenniss** [comment]
LG, but I don't think we should change the year. New files would get the current year, existing files should probably retain their year of creation.

---

Review status: 0 of 58 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/47#-:-KFuHAO5YyOzLb1qgEDJ:1139234406)*

**Comment by iainmcgin** [comment]
OK, switched to 2015.

---

Review status: 0 of 58 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/47#-:-KFuTiasr4Cpw_H3s7Iv:-632903137)*

**Comment by WilliamDenniss** [comment]
:lgtm:

---

Review status: 0 of 58 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/47#-:-KFuWJ5LHO31gBHSaO9n:1417088721)*

**Pull request merged**
