### PR TITLE
Add support for OpenID Connect 1.0 display param

### PR DESCRIPTION
**Pull request by iainmcgin**
Implements #13

---
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/33) &emsp; Multiple assignees:&emsp;@WilliamDenniss&nbsp;<a href="/openid/appauth-android/pulls/assigned/WilliamDenniss">WilliamDenniss</a>,&emsp;@tikurahul&nbsp;<a href="/openid/appauth-android/pulls/assigned/tikurahul">tikurahul</a>

### CODE REVIEW

**Comment by iainmcgin** [comment]
+@tikurahul  +@williamdenniss  for review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/33#-:-KDC_PF2HOm6zFuARhC_:1777822592)*

**Comment by WilliamDenniss** [comment]
I wonder if anyone is using this param? I don't think we do, and it seems a bit outdated now there are better ways to do this (i.e. responsive design).

That said, I believe your implementation of this param is correct.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[library/java/net/openid/appauth/AuthorizationRequest.java, line 278 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/33#-KDGHTd8Mmj05jpG4R__:-KDGHTd8Mmj05jpG4R_a:1760093461) ([raw file](https://github.com/openid/appauth-android/blob/1d42ed447f85af8f7cac50a3bfc3951e93f68775/library/java/net/openid/appauth/AuthorizationRequest.java#L278)):*
This should be "display"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/33#-:-KDGHb28cdLIeYmiYBSg:2630242)*

**Comment by iainmcgin** [comment]
I don't know if anyone is using it, but it was at least one of the simpler ones to implement. If anyone is using this, it is likely with custom values rather than those defined in the spec, which seem pretty useless in 2016.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[library/java/net/openid/appauth/AuthorizationRequest.java, line 278 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/33#-KDGHTd8Mmj05jpG4R__:-KDGl9rVTUh99eem1sEy:1981749878) ([raw file](https://github.com/openid/appauth-android/blob/1d42ed447f85af8f7cac50a3bfc3951e93f68775/library/java/net/openid/appauth/AuthorizationRequest.java#L278)):*
Good catch - Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/33#-:-KDGlLjH6gd9y8VRIaM_:-1085043383)*

**Comment by WilliamDenniss** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/33#-:-KDKyBhHGQ3hhvGE7b_d:1417088721)*

**Comment by WilliamDenniss** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/33)*

**Comment by ve7jtb** [comment]
We did have someone ask about it recently.   It was something that I think originally came from Facebook.  It was a holdover from openID 2.

There was another spec in openid 2 that defined the size of the popup that the RP creates.  

In the wild it was mostly JainRain that used it for there Identity as a service to avoid taking the user out of the RP context.

It should probably be deprecated at some point.

John B.

**Pull request merged**
