### PR TITLE
Use an intermediary activity to manage the authorization flow

### PR DESCRIPTION
**Pull request by iainmcgin**
This change fixes issues #106, #104 and #102.

   * #106 - By forwarding the OAuth redirect to the management activity via an Intent with SINGLE_TOP and CLEAR_TOP flags set, we can dispose of the browser tab without using the NO_HISTORY flag. The browser flow will survive the user switching tasks, and will not appear in the back stack after the authorization flow completes.

   * #104 - All state pertinent to the authorization request is stored as instance state on the activity. If the activity is completely killed under memory pressure during the authorization flow, everything should still work as intended once the application's activities are restored. This removes the need for PendingIntentStore, which was using a static map to store this information previously.

   * #102 - By introducing the intermediary activity, we can detect when this is resumed without receiving the redirect from the authorization flow in the browser. This is a signal that the user canceled the flow by pressing the back button or closing the tab. Based on this, we can fire different PendingIntent to indicate the flow was canceled.

The changes *should* be backwards compatible. We have also simplified the configuration of the redirect URI receiver activity, using a manifest merge attribute set in the build file.

---
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/109)

### CODE REVIEW

**Comment by iainmcgin** [comment]
+@tikurahul / +@williamdenniss for review.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/109#-:-KSOdQZeU2vbPAU6AZDk:b-k2q5hp)*

**Comment by tikurahul** [comment]
:lgtm_strong: 

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/109#-:-KSOhfsbFWLCiwYREsma:b-uwkowd)*

**Comment by ccarrasc** [comment]
Nice! Any plans to publish/release this soon?

**Comment by iainmcgin** [comment]
Yeah, I'll try and cut a 0.4.0 release next week with this change. I just want to make sure I'm not breaking any expected behavior with this change first.

**Pull request merged**
