### PR TITLE
Update Configuration example in README.

### PR DESCRIPTION
**Pull request by rebeckag**
AuthorizationServiceConfiguration.fetchFromIssuer has no return value.
Only use variable in scope in log message.

---
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/65)

### CODE REVIEW

**Comment by iainmcgin** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 164 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/65#-KGmyzJx_4U_gLWg_uUn:-KGmyzJx_4U_gLWg_uUo:355527787) ([raw file](https://github.com/openid/appauth-android/blob/f827e9dee347cc89aa80cf73e0140c21b204d8e0/README.md#L164)):*
Please keep the config variable definition - it is referenced in subsequent sections.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/65#-:-KGmzBaUfuH9-AJHOk_4:980077423)*

**Comment by rebeckag** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[README.md, line 164 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/65#-KGmyzJx_4U_gLWg_uUn:-KGospBL4IMTLzTcNkgq:-499146009) ([raw file](https://github.com/openid/appauth-android/blob/f827e9dee347cc89aa80cf73e0140c21b204d8e0/README.md#L164)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/65)*

**Comment by iainmcgin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[README.md, line 164 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/65#-KGtB5tTYdXOWHQZXGBY:-KGtB5tTYdXOWHQZXGBZ:1654535949) ([raw file](https://github.com/openid/appauth-android/blob/ef116d97ccbe544b25d07de0dac6416f38f8333e/README.md#L164)):*
looks like you accidentally terminated this line rather than kept the original assignment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/65)*

**Comment by rebeckag** [comment]
*[README.md, line 164 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/65#-KGtB5tTYdXOWHQZXGBY:-KGvReXG_avhPWzKcdLl:-1810619079) ([raw file](https://github.com/openid/appauth-android/blob/ef116d97ccbe544b25d07de0dac6416f38f8333e/README.md#L164)):*
Then I misunderstood your previous comment. I removed the assignment in the original change, since `AuthorizationServiceConfiguration.fetchFromIssuer` doesn't return a value. Should it still be kept?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/65)*

**Comment by iainmcgin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[README.md, line 164 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/65#-KGtB5tTYdXOWHQZXGBY:-KGwS47Bj_Xw18p2UVAI:1670951695) ([raw file](https://github.com/openid/appauth-android/blob/ef116d97ccbe544b25d07de0dac6416f38f8333e/README.md#L164)):*
Oh, that's my fault for skimming code with false assumptions :) the assignment would be within your else branch, but then of course it would have to be a field to actually work. It's fine to leave this as-is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/65)*

**Pull request merged**
