### PR TITLE
Create README-Gluu.md

### PR DESCRIPTION
**Pull request by arvindsinghtomar**
Readme File file to use AppAuth demo with the Gluu server

### CODE REVIEW

**Comment by nynymike** [comment]
This is just the Readme.  Thanks in advance for your quick review!

**Comment by nynymike** [comment]
I still don't see it in [https://github.com/openid/AppAuth-Android/tree/master/app](https://github.com/openid/AppAuth-Android/tree/master/app)

**Comment by tikurahul** [comment]
I approved it. Iain still needs to merge it. Sorry I don’t have the permissions.

**Comment by iainmcgin** [comment]
Done - I was out sick yesterday, sorry for the delay.

**Pull request merged**
