### PR TITLE
Add support for custom tabs in Firefox

### PR DESCRIPTION
**Pull request by hnljp**
support for custom tabs was added to stable Firefox in version 57.0

fixes: #368
Signed-off-by: Henning Nielsen Lund <henning.n.lund@jp.dk>

### CODE REVIEW

**Comment by iainmcgin** [comment]
If you can separate the commits so that the firefox custom tab definitions can be pulled in separately from the rest, I can merge that piece at least. The default browser behavior needs some more discussion and investigation.

**Comment by hnljp** [comment]
The ordered list is always returning Chrome as the first entry, no matter what...
This is an example, of a phone with Android 8.0, where Firefox is set as the default browser: 07-14 22:15:15.714 12422-12909/? D/BrowserSelector: resolvedActivityList: [ResolveInfo{3be23c com.android.chrome/com.google.android.apps.chrome.Main m=0x108000}, ResolveInfo{ed5cbc5 org.mozilla.firefox/.App m=0x108000}] 
I do not know what their criteria is for the order, but it is not returning the default browser first.
The same is also shown on Android 7.0.

**Comment by hnljp** [comment]
it could be changed if the flag used by queryIntentActivities was changed.

**Comment by hnljp** [comment]
I have tried to look more into it.
The problem is that the PackageManager.MATCH_ALL flag is making the result unsorted.
https://developer.android.com/reference/android/content/pm/PackageManager#MATCH_ALL
But the problem is that removing MATCH_ALL, will make queryIntentActivities only return the default browser on Android >= 7.0.

Looking at the code generating the list returned by queryIntentActivities:
https://android.googlesource.com/platform/frameworks/base.git/+/master/services/core/java/com/android/server/pm/PackageManagerService.java#7801
That is using the list generated as "an unsorted list":
https://android.googlesource.com/platform/frameworks/base.git/+/master/services/core/java/com/android/server/pm/PackageManagerService.java#7731
That is why there is a need to get the package name of the default browser and the list using MATCH_ALL is needed, in case the default browser is not compatible with Custom Tabs.

**Comment by iainmcgin** [comment]
OK, thanks for investigating further. Could you still separate this change into two pull requests, one for adding the additional constants related to Firefox, and the other for the default browser selection?

**Comment by hnljp** [comment]
Have made a new pull request only including the Firefox support.
Better to separate the two issues, as stated by iainmcgin
https://github.com/openid/AppAuth-Android/pull/378

**Comment by hnljp** [comment]
Have created a new pull request regarding using the default browser, if it is compatible.
https://github.com/openid/AppAuth-Android/pull/379

**Review by Hkoma95 — APPROVED** [review]

**Pull request closed without merging**
