### PR TITLE
Implement ui_locales parameter support.

### PR DESCRIPTION
**Pull request by ivan9jukic**
Implements #16

### CODE REVIEW

**Comment by mavdi** [comment]
Can this PR be merged? Is anything holding it up?

**Review by agologan — APPROVED** [review]

**Comment by agologan** [comment]
@ivan9jukic I know this is an old contribution but could you please sign the CLA agreements https://github.com/openid/AppAuth-Android/blob/master/CONTRIBUTING.md

**Comment by arok** [comment]
Any updated on this?

**Comment by hnljp** [comment]
> Any updated on this?

Personally I simply use the already existing method setAdditionalParameters, to set "ui_locales" with a corresponding value.

**Comment by ivan9jukic** [comment]
> @ivan9jukic I know this is an old contribution but could you please sign the CLA agreements https://github.com/openid/AppAuth-Android/blob/master/CONTRIBUTING.md

@agologan Done!

**Comment by agologan** [comment]
Unfortunately I don't see your CLA listed. Do you mind linking it from the openid website?

**Comment by cumcum8197** [comment]
45589c704042755cdbc85e8a8b301837e6e2f5f4

**Pull request merged**
