### PR TITLE
Add GH actions

### PR DESCRIPTION
**Pull request by dulmandakh**
### Checklist
- [x] I read the [Contribution Guidelines](https://github.com/openid/AppAuth-Android/blob/master/CONTRIBUTING.md)
- [x] I signed the CLA and WG Agreements 
- [x] I ran, updated and added unit tests as necessary.
- [ ] I verified the contribution matches existing coding style.
- [ ] I updated the documentation if necessary.

### Motivation and Context
Add GH Actions as CI

### Description
Add GH Actions as CI, on push and pull_request events https://github.com/dulmandakh/AppAuth-Android/actions/runs/568648814

### CODE REVIEW

**Comment by agologan** [comment]
I'm sorry but could you please explain why you're proposing we move from Travis to GH Actions?

**Comment by dulmandakh** [comment]
It's more integrated with GH and usually it's faster.

**Comment by agologan** [comment]
I understand the appeal but can't find a good enough argument to move over.
Will defer to @iainmcgin as he'll have to import the codecov config to have parity.

**Comment by agologan** [comment]
Reconsidered my stance and decided migrating to GH Actions is alright.
Updated your proposed change fixing up the style and removing the travis config.

**Comment by dulmandakh** [comment]
@agologan thanks 👍

**Comment by cumcum8197** [comment]
d61599bfe7fac440ca7fb554c4720bd0bab3cf3b

**Pull request merged**
