### PR TITLE
Be more lenient about refresh tokens

### PR DESCRIPTION
**Pull request by rebeckag**
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/42)

### CODE REVIEW

**Comment by iainmcgin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/openid/appauth-android/42#-KEBtuW1ibXf1v3g3E9k:-KEBtuW1ibXf1v3g3E9l:674447248) (no related file):*
I'm not sure what the right behavior should be here - as it stands, the call to `getNeedsTokenRefresh` will always return false if no refresh token has been acquired. The proposed change will always call the action with the current tokens, regardless of whether they are stale, which seems bad. 

Even if we do check if the tokens are stale independent of the refresh token, there isn't anything we can automatically do to refresh it without a refresh token.

A compromise could be that we call the action with an authorization exception if the tokens have become stale. This would allow the action to take remedial action, such as starting a new authorization request. Generally speaking, though, I feel `performActionWithFreshTokens` is only really useful when you have short-lived tokens and a refresh token you can use to replace them as needed.

Any thoughts?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/42)*

**Comment by rebeckag** [comment]
*[a discussion](https://reviewable.io:443/reviews/openid/appauth-android/42#-KEBtuW1ibXf1v3g3E9k:-KECO4eGHJFw1tijOvBK:-1216265128) (no related file):*
Your solution for a compromise, signalling a stale token with an AuthorizationException sounds good to me!

Because although I agree with your opinion of the usage for `performActionWithFreshTokens`, I only discovered this being an issue after modifying the demo app to work against one of my provider instances for test which doesn't issue refresh tokens. Instead it issues access tokens without expiration time. It would be nice if this case (however unusual it might be, I don't know?) automagically works, to off-load work from developers using the SDK.
It seems an unnecessary burden (for developers) to differ between providers which issues long-lived tokens and providers who issues short-lived tokens together with refresh tokens.

Should I implement the following change: if there is no refresh token and the access token has expired; call `action.execute` with a new AuthorizationException instace, containing a message like 'Access token has expired and can't be refreshed'. Do you have any other text suggestion for it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/42)*

**Comment by iainmcgin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/openid/appauth-android/42#-KEBtuW1ibXf1v3g3E9k:-KECUOywMxfTq-bPwetv:-584376682) (no related file):*
If the access token never expires, then there is no real need to use `performActionWithFreshTokens`, which is why I am hesitant to establish the pattern of using it in this case. It might make sense for consistency if an app is using more than one IDP and wishes to manage authenticated calls in the same way, regardless of the properties of the retrieved tokens.

I'll discuss this with @williamdenniss, as we'll want to make sure the behavior is consistent between iOS and Android no matter how we choose to address this. Our AuthorizationException based compromise seems like the only sensible way to present a consistent interface.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/42)*

**Comment by WilliamDenniss** [comment]
Interesting use-case of returning an infinite lived access token and no refresh token, but not completely unheard of actually and it [doesn't](https://tools.ietf.org/html/rfc6749#section-5.1) violate the spec.

I think I'm in favor of the consistency argument, we want to encourage use of `performActionWithFreshTokens` over accessing the access token directly, and like you say @iainmcgin, this would allow use of `performActionWithFreshTokens` with IDPs that don't return refresh tokens mixed in with ones that do.  Even if the access token was shorter lived than infinite, it is still a valid pattern – the app should handle the error and attempt to re-auth the user.

Regarding the implementation, I wonder if we should be consistent in the way we pass the error to the App. As it stands, if a refresh token exists but was invalid, and an `invalid_grant` error recieved, it would be handled differently (passed in `action.execute(null, null, ex)` than when no refresh_token exists at all (exception thrown), and yet in both cases the app would need to re-auth the user.

**Comment by rebeckag** [comment]
I absolutely think it would be preferable to be consistent in the two cases @WilliamDenniss raises, invalid refresh token and no refresh token, since as you say they have the same consequence (need to re-auth the user).

**Comment by WilliamDenniss** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[library/java/net/openid/appauth/AuthState.java, line 391 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/42#-KEraFmaZu6wspa1rqyk:-KEraFmaZu6wspa1rqyl:-706520226) ([raw file](https://github.com/openid/appauth-android/blob/ca33877ff94a56edff73e27b1eda672028db06fa/library/java/net/openid/appauth/AuthState.java#L391)):*
So should we replace the throw with something like:

IllegalStateException ex = new IllegalStateException("No refresh token available");
action.execute(null, null, ex);

Any thoughts @iainmcgin ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/42)*

**Comment by ve7jtb** [comment]
Both a invalid access token and a revoked refresh token should indicate back to the app to reauth.  They should probably look the same.   It is legitimate to revoke access tokens at the RS out of band eg by introspection.   I see both patterns with AS.

**Comment by iainmcgin** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[library/java/net/openid/appauth/AuthState.java, line 391 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/42#-KEraFmaZu6wspa1rqyk:-KF4PiT1IYpl9d7ONQFw:-1620340330) ([raw file](https://github.com/openid/appauth-android/blob/ca33877ff94a56edff73e27b1eda672028db06fa/library/java/net/openid/appauth/AuthState.java#L391)):*
I think with the discussion to this point it would make sense for any failures in this flow to be presented to the action as an exception. The interface requires an `AuthorizationException`, so we could pass `AuthorizationRequestErrors.CLIENT_ERROR` in this case, with the explanatory string set appropriately:

```
AuthorizationException ex = 
    AuthorizationException.fromTemplate(
        AuthorizationRequestErrors.CLIENT_ERROR,
        new IllegalStateException("No refresh token available and tokens have expired");
```

Could you make this change, Rebecka?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/42)*

**Comment by rebeckag** [comment]
*[library/java/net/openid/appauth/AuthState.java, line 391 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/42#-KEraFmaZu6wspa1rqyk:-KF8PC6PSnsE6e-l1DB0:-499146009) ([raw file](https://github.com/openid/appauth-android/blob/ca33877ff94a56edff73e27b1eda672028db06fa/library/java/net/openid/appauth/AuthState.java#L391)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/42)*

**Comment by iainmcgin** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/42#-:-KFAILCAo1G4VXtH7RhA:1417088721)*

**Pull request merged**
