### PR TITLE
fix #318 NPE on AuthorizationManagementActivity.onResume

### LINKED ISSUE #318: NPE on AuthorizationManagementActivity.onResume (from Android framework?)
I can't reproduce it myself, but on an app with around half million active users it's happening on production from time to time. (we are using the latest AppAuth version 0.7.0).

Usually happening on these devices:
- Huawei 荣耀5X (HNKIW-Q) [Android 6.0]
- Galaxy TabS 10.5 (chagalllte) [Android 6.0]
- Gigaset GS170 (GS170) [Android 7.0]
- Galaxy J1 (j13g) [Android 4.4]
- Samsung Galaxy S5 mini (kminilte) [Android 6.0]

NPE:
> java.lang.NullPointerException: android.app.Instrumentation
> in Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference.execStartActivity

Stack trace:
```
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4225)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4327)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3426)
at android.app.ActivityThread.access$1100(ActivityThread.java:229)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:7331)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1534)
at android.app.Activity.startActivityForResult(Activity.java:4298)
at android.app.Activity.startActivityForResult(Activity.java:4245)
at android.app.Activity.startActivity(Activity.java:4582)
at android.app.Activity.startActivity(Activity.java:4550)
at net.openid.appauth.AuthorizationManagementActivity.onResume(AuthorizationManagementActivity.java)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1287)
at android.app.Activity.performResume(Activity.java:7015)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4214)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4327)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3426)
at android.app.ActivityThread.access$1100(ActivityThread.java:229)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:7331)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

### PR DESCRIPTION
**Pull request by phusung**
Fixed by restoring values

### CODE REVIEW

**Comment by iainmcgin** [comment]
Have you signed the CLA?

**Comment by WilliamDenniss** [comment]
@phusung please provide the link to your signed [CLA](http://openid.net/intellectual-property/contribution-license-agreement/).

**Comment by iainmcgin** [comment]
Closing as no response on signing the CLA.

**Comment by Fideas** [comment]
Is the code in this PR the right solution to the issue? I'm asking to know if it is helpful that I send another PR with the same changes, and sign the CLA so we can have this fixed

**Comment by phusung** [comment]
Dear Nicolás,

It's bug cause the null pointer on resume function.
Finally, I was fixed by try to restore the value.
Please see attached file.
Hope to help,

Best regards,

**Comment by Fideas** [comment]
I have seen the file, the problem is that I would rather import the library through gradle, rather than having to keep my own copy of it with just that modification

**Pull request closed without merging**
