### PR TITLE
Store RegistrationResponse in AuthState.

### PR DESCRIPTION
**Pull request by rebeckag**
Make use of the stored RegistrationResponse when constructing token requests in the TokenActivity of the demo app.

---
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/61)

### CODE REVIEW

**Comment by iainmcgin** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[app/src/net/openid/appauthdemo/MainActivity.java, line 89 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGYF1B_XSDZZoGaBbeA:-KGYF1BasSukZKRsaiKq:-1122542000) ([raw file](https://github.com/openid/appauth-android/blob/7bfc5491dbd2641f274377dcaa91961683637678/app/src/net/openid/appauthdemo/MainActivity.java#L89)):*
Pass in `new AuthState()` here instead of null, which should simplify the later handling of updating the AuthState in TokenActivity.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 120 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGYFWkR9fgHpgxBDnvo:-KGYFWkR9fgHpgxBDnvp:-1273696694) ([raw file](https://github.com/openid/appauth-android/blob/7bfc5491dbd2641f274377dcaa91961683637678/app/src/net/openid/appauthdemo/TokenActivity.java#L120)):*
this conditional should disappear after you ensure an AuthState instance is always available from the intent.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 275 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGYFiKvXLBD0j7KKdaZ:-KGYFiKwZmFkakmT0pb_:-975821711) ([raw file](https://github.com/openid/appauth-android/blob/7bfc5491dbd2641f274377dcaa91961683637678/app/src/net/openid/appauthdemo/TokenActivity.java#L275)):*
We should generalize this by adding a new method to AuthState that can provide a `ClientAuthentication` instance based on the properties found in the registration request and response. Something like:

```
public ClientAuthentication getClientAuthentication() {
    if (mLastRegistrationResponse == null) {
        return NoClientAuthentication.INSTANCE;
    }

    switch (mLastRegistrationResponse.request.tokenEndpointAuthenticationMethod) {
        case ClientSecretBasic.NAME: 
            return new ClientSecretBasic(mLastRegistrationResponse.clientSecret);
        case ClientSecretPost.NAME: 
            return new ClientSecretPost(mLastRegistrationResponse.clientSecret);
        default: 
            return NoClientAuthentication.INSTANCE;
    }
}
```

---

*[library/java/net/openid/appauth/AuthState.java, line 419 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGYIwnQEK8VISbsK025:-KGYIwnRuQOfdJ-9PO9I:1178929733) ([raw file](https://github.com/openid/appauth-android/blob/7bfc5491dbd2641f274377dcaa91961683637678/library/java/net/openid/appauth/AuthState.java#L419)):*
Should a new registration response invalidate (clear) any existing authorization response / token response? This seems likely, as the client ID would change?

---

*[library/javatests/net/openid/appauth/AuthStateTest.java, line 1 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGYJwPjLa1xkx_bz76-:-KGYJwPjLa1xkx_bz760:-1362117020) ([raw file](https://github.com/openid/appauth-android/blob/7bfc5491dbd2641f274377dcaa91961683637678/library/javatests/net/openid/appauth/AuthStateTest.java#L1)):*
the `check` task in the build is complaining you have some unused imports in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/61)*

**Comment by rebeckag** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/net/openid/appauthdemo/MainActivity.java, line 89 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGYF1B_XSDZZoGaBbeA:-KGkTQHrG7Mg9-L-z3qk:-499146009) ([raw file](https://github.com/openid/appauth-android/blob/7bfc5491dbd2641f274377dcaa91961683637678/app/src/net/openid/appauthdemo/MainActivity.java#L89)):*
Done.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 120 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGYFWkR9fgHpgxBDnvo:-KGkTYdSndRHqyRcQVFN:-499146009) ([raw file](https://github.com/openid/appauth-android/blob/7bfc5491dbd2641f274377dcaa91961683637678/app/src/net/openid/appauthdemo/TokenActivity.java#L120)):*
Done.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 275 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGYFiKvXLBD0j7KKdaZ:-KGkVrSUl7UpJAdItKAg:1271634753) ([raw file](https://github.com/openid/appauth-android/blob/7bfc5491dbd2641f274377dcaa91961683637678/app/src/net/openid/appauthdemo/TokenActivity.java#L275)):*
This is much nicer!

I implemented your suggestion with some modifications:
1. We can't look at any parameters in the registration request since the identity provider is free to ["reject or replace any of the Client's requested field values and substitute them with suitable values"](https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationResponse). The OP returns all registered metadata for the client, so we can look straight at the registration response (`mLastRegistrationResponse.tokenEndpointAuthenticationMethod`).
2. Explicitly handle the case `"none"`.
3. Let the default case throw an exception since the library can't gracefully handle an unknown client authentication method. `NoClientAuthentication` will probably not work (since the case `"none"` is explicitly handled), so we can save the network round-trip by reporting this and let an implementer deal with any custom authentication methods.

Done.

---

*[library/java/net/openid/appauth/AuthState.java, line 419 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGYIwnQEK8VISbsK025:-KGka3VsFkh5wrf2KCqP:-734281123) ([raw file](https://github.com/openid/appauth-android/blob/7bfc5491dbd2641f274377dcaa91961683637678/library/java/net/openid/appauth/AuthState.java#L419)):*
We touched on this discussion previously, and I'm a bit unsure of the full extent of a new registration. There are some different parts:
1. If the access token is a Bearer token it could technically still be used (since anyone in possession of it can use it, the new client id won't matter).
2. The refresh token on the other hand can't be used with an OP which enforces client authentication at the token endpoint (the authentication with a new client id/client secret won't match the client id bound to the refresh token).
3. The last authorization and token response is definitely invalid, since they represent a session for the user with another client (another client id).

I've updated the change to invalidate the entire AuthState (`mRefreshToken`, `mScope`, `mLastAuthorizationResponse`, `mLastTokenResponse`,  and `mAuthorizationException`). Maybe this can be improved in a future implementation, but it should be sufficient for now.

Done.

---

*[library/javatests/net/openid/appauth/AuthStateTest.java, line 1 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGYJwPjLa1xkx_bz76-:-KGkjCtaExqYyWxWy6Po:-114711295) ([raw file](https://github.com/openid/appauth-android/blob/7bfc5491dbd2641f274377dcaa91961683637678/library/javatests/net/openid/appauth/AuthStateTest.java#L1)):*
Sorry about that!
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/61)*

**Comment by iainmcgin** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 369 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGmfjo6aiC1VJXJWVfk:-KGmfjo7UNTudUQlelpX:-288367082) ([raw file](https://github.com/openid/appauth-android/blob/61e0f2d683b7b56850f09c565390507d5597e6b3/app/src/net/openid/appauthdemo/TokenActivity.java#L369)):*
This should be `@NonNull` now, I think.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 376 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGmfsk5qR27cnyvPktr:-KGmfsk5qR27cnyvPkts:-1188042313) ([raw file](https://github.com/openid/appauth-android/blob/61e0f2d683b7b56850f09c565390507d5597e6b3/app/src/net/openid/appauthdemo/TokenActivity.java#L376)):*
No need for the conditional here if we require that authState is non-null.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 395 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGmfx5MS8uQpUCeUPmH:-KGmfx5MS8uQpUCeUPmI:1362477252) ([raw file](https://github.com/openid/appauth-android/blob/61e0f2d683b7b56850f09c565390507d5597e6b3/app/src/net/openid/appauthdemo/TokenActivity.java#L395)):*
This should actually be an error condition (throw unchecked exception), as an AuthState instance is now required.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 401 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGmg93zR93EfVnxFpd2:-KGmg93zR93EfVnxFpd3:1221395769) ([raw file](https://github.com/openid/appauth-android/blob/61e0f2d683b7b56850f09c565390507d5597e6b3/app/src/net/openid/appauthdemo/TokenActivity.java#L401)):*
Similarly, I think you should throw an exception here, as without an AuthState instance the TokenActivity cannot function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/61)*

**Comment by rebeckag** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 369 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGmfjo6aiC1VJXJWVfk:-KGoxuAsUtLmmxdzQSjK:-499146009) ([raw file](https://github.com/openid/appauth-android/blob/aa8c94f406d1872259560e7dd700f51efd713f58/app/src/net/openid/appauthdemo/TokenActivity.java#L369)):*
Done.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 376 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGmfsk5qR27cnyvPktr:-KGowGanOgrd6dcrh2vY:-499146009) ([raw file](https://github.com/openid/appauth-android/blob/aa8c94f406d1872259560e7dd700f51efd713f58/app/src/net/openid/appauthdemo/TokenActivity.java#L376)):*
Done.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 395 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGmfx5MS8uQpUCeUPmH:-KGoxBUVuGfpUfQ7sKvy:-499146009) ([raw file](https://github.com/openid/appauth-android/blob/aa8c94f406d1872259560e7dd700f51efd713f58/app/src/net/openid/appauthdemo/TokenActivity.java#L395)):*
Done.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 401 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGmg93zR93EfVnxFpd2:-KGoxBrApQwZAEGbAc-C:-499146009) ([raw file](https://github.com/openid/appauth-android/blob/aa8c94f406d1872259560e7dd700f51efd713f58/app/src/net/openid/appauthdemo/TokenActivity.java#L401)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/61)*

**Comment by iainmcgin** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/net/openid/appauthdemo/TokenActivity.java, line 395 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGmfx5MS8uQpUCeUPmH:-KGtBQE4tet6q5s5bY4U:753735249) ([raw file](https://github.com/openid/appauth-android/blob/aa8c94f406d1872259560e7dd700f51efd713f58/app/src/net/openid/appauthdemo/TokenActivity.java#L395)):*
IllegalArgumentException is preferable to RuntimeException.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/61)*

**Comment by rebeckag** [comment]
*[app/src/net/openid/appauthdemo/TokenActivity.java, line 395 \[r2\]](https://reviewable.io:443/reviews/openid/appauth-android/61#-KGmfx5MS8uQpUCeUPmH:-KGvSPdSH-3oRX82x5h4:1673873034) ([raw file](https://github.com/openid/appauth-android/blob/aa8c94f406d1872259560e7dd700f51efd713f58/app/src/net/openid/appauthdemo/TokenActivity.java#L395)):*
Of course (I at least got it right in the other place :)).
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/61)*

**Comment by iainmcgin** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/61#-:-KGwRVvm1irV-Hc63XEX:1417088721)*

**Pull request merged**
