### PR TITLE
Provide response URI on completion

### PR DESCRIPTION
**Pull request by witrisna**
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/133)

### CODE REVIEW

**Comment by witrisna** [comment]
Everything is included in the AuthorizationResponse, however, when something goes wrong (e.g state mismatch), it will be better if the application has access to the raw response URI to identify the issue.

**Comment by witrisna** [comment]
In another scenario: Other than the authorization code and the state, the Authorization Server may responses other parameters that the client may recognize.
For example:   
HTTP/1.1 302 Found
     Location: https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA
               &state=xyz&**expires_in= 3600**
According to [RFC 6749 4.1.2](https://tools.ietf.org/html/rfc6749#section-4.1.2), the "The client MUST ignore unrecognized response parameters.". The client should allow exchanging additional information if the parameter is predefined between the client and authorization server.

**Comment by iainmcgin** [comment]
For your second scenario, additional non-standard parameters should already be extracted into the additionalParameters field of TokenResponse:

https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/TokenResponse.java#L219

I can include this change, it's fairly low impact, though documentation should be added to explain that the full URI is provided in the manner you are proposing. Please add that. Additionally, have you signed the OpenID CLA?

**Comment by witrisna** [comment]
Documentation has been added, and I have signed the OpenID CLA.

**Pull request merged**
