### PR TITLE
Replace your-custom-scheme by "reverse domain name notation"

### PR DESCRIPTION
**Pull request by AxelNennker**
https://tools.ietf.org/html/draft-ietf-oauth-native-apps-07#section-3

### CODE REVIEW

**Comment by iainmcgin** [comment]
Could you (preferably your employer) sign the [contribution license agreement](http://openid.net/intellectual-property/contribution-license-agreement/)? We'll need that before I can accept the change.

**Comment by iainmcgin** [comment]
Also, don't worry about the coverage report complaining. I only pay attention to that where code is concerned, though I agree it's annoying.

**Comment by AxelNennker** [comment]
done. CLA signed and sent to help@oidf.org

**Comment by ve7jtb** [comment]
Thanks Axel.

John B.

**Pull request merged**
