### PR TITLE
Move request URI generation into AuthorizationRequest

### PR DESCRIPTION
**Pull request by iainmcgin**
[Review on Reviewable](https://reviewable.io/reviews/openid/appauth-android/1)

### CODE REVIEW

**Comment by iainmcgin** [comment]
+@WilliamDenniss for review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/1#-:-KBVcQLWfmejmXPtmYiB:2061413712)*

**Comment by tikurahul** [comment]
LGTM

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/1#-:-KBVezqoeFojsHqpv60d:676834233)*

**Comment by WilliamDenniss** [comment]
LGTM

**Comment by sbnewsthailand** [comment]
> 
> 
> [Review on Reviewable](https://reviewable.io/reviews/openid/appauth-android/1)
> 
> 
>

**Review by sbnewsthailand — APPROVED** [review]

**Pull request merged**
