### PR TITLE
Update AuthState persistence documentation

### PR DESCRIPTION
**Pull request by sudonatalie**

### CODE REVIEW

**Comment by mavdi** [comment]
Is this repo abandoned? Nothing has been merged lately.

**Comment by iainmcgin** [comment]
See #444 - I don't have the time to stay on top of maintenance for this project anymore, and we haven't had anyone else firmly commit to owning the project.

**Comment by kadirselcuk** [comment]
Continue with codecov report for authstate updates of permanent documents

**Review by blundell — APPROVED** [review]
LGTM

**Pull request merged**
