### PR TITLE
Change launchMode to singleTop

### PR DESCRIPTION
**Pull request by hnljp**
Changing the lauchMode to singleTop fixes the problem with Android < 5.0

Tested with customTabs and stand alone browsers and it is working. The problem that was experienced with singleInstance is not pressent with singleTop: https://github.com/openid/AppAuth-Android/issues/170#issuecomment-280952807

Fixes: https://github.com/openid/AppAuth-Android/issues/299
Signed-off-by: Henning Nielsen Lund <henning.n.lund@jp.dk>

### CODE REVIEW

**Comment by hnljp** [comment]
Tested on both Android 4.2.2 and Android 8.0.
Tested with Chrome and Firefox, both with and without CustomTabs.
Everything has been working fine, on both OS versions.

**Comment by iainmcgin** [comment]
I'll need to ponder on this, I was under the impression that singleTop would have a different set of issues. I'll discuss with my Android colleagues to see if we can remember what those issues were, or if we had just confused ourselves when trying to solve the original issue.

**Comment by hnljp** [comment]
That is fine. So far I have seen no difference on Android >= 5.0, but there could be a scenario that I have not tested.

**Comment by hnljp** [comment]
We no longer support Android < API21

**Pull request closed without merging**
