### PR TITLE
Implementation of browser filtering for authorization requests

### LINKED ISSUE #116: Apparent bug in Samsung's "Internet" Browser's custom tab implementation
My company's use of AppAuth hit a snag when we couldn't login on our Galaxy S7 and Galaxy S7 Edge test devices in their factory-default setting which is using Samsung's "Internet" as the default browser.  This browser apparently is also a Custom Tabs provider, and it appears that when using Samsung's Custom Tabs implementation it eats the redirect URIs.

What I mean is this: our Android app registers as the handler for a particular URI, and our login server redirects to that URI at the end of the login process -- but Android never gets that redirect and control never returns to our app once login is complete.  When we switch to using Chrome Custom Tabs, everything works as expected.

We're currently experimenting with our URIs to see if it only eats certain URI pattern, and we'll also be filing an issue with Samsung.  We've currently worked around the issue by making a local fork of AppAuth and hard-coding a "Use Chrome's Custom Tabs" rule.

Have you considered allowing AppAuth users to have more control over which Custom Tabs implementations the do (or do not) want to use?

### PR DESCRIPTION
**Pull request by iainmcgin**
This gives apps more control over the browsers that can be used
for the authorization flow. Fixes #116, #114, #113.

---
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/119)

### CODE REVIEW

**Comment by iainmcgin** [comment]
+@tikurahul / +@williamdenniss for review.

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/119#-:-KUKtLjqps5Tf5eDC2Jc:b-k2q5hp)*

**Comment by tikurahul** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/119)*

**Comment by tikurahul** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/119#-:-KUPIL6peBZTFXXhmST8:b-uwkowd)*

**Comment by mattinger** [comment]
Any updated on 0.4.0?  It does not seem to have been published yet.

**Comment by iainmcgin** [comment]
Sorry, I was out sick on Friday and Monday, back at it now. I just want to confirm I haven't broken anything for interaction with external (non-custom tab) browsers before I push a new version.

**Comment by iainmcgin** [comment]
0.4.0 is now pushed to jcenter - please let me know if you have any issues.

**Pull request merged**
