### PR TITLE
And 1515/refactor app auth to support multiple scopes

### PR DESCRIPTION
**Pull request by kmdupr33**

### CODE REVIEW

**Comment by WilliamDenniss** [comment]
Can all the contributors to this PR please sign [CLAs](http://openid.net/intellectual-property/contribution-license-agreement/)? NB. a corporate CLA is also available.

**Comment by hnljp** [comment]
@kmdupr33 You should make a direct fork of AppAuth-Android and add your change https://github.com/openid/AppAuth-Android/pull/391/commits/bea3a14234bff4ef0c2571977150fd65f389ea5a
At the moment your pull request includes the redirect changes of unikey.

**Comment by iainmcgin** [comment]
I'm not sure I understand the purpose of this change - in OAuth2, multiple scopes are expressed via a space delimited list of scope identifiers, which the library already supports. We even provides utility methods to allow for the scope strings to be specified as separate strings:

https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationRequest.java#L742

Could you clarify why these changes are necessary?

**Comment by kmdupr33** [comment]
Yikes. I actually didn't intend to submit a pr against this repo. My apologies.

**Pull request closed without merging**
