### PR TITLE
Add support for OpenID Connect 1.0 prompt param

### PR DESCRIPTION
**Pull request by iainmcgin**
Implementation for #14 
+@tikurahul +@WilliamDenniss for review

---
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/31) &emsp; Multiple assignees:&emsp;@WilliamDenniss&nbsp;<a href="/openid/appauth-android/pulls/assigned/WilliamDenniss">WilliamDenniss</a>,&emsp;@tikurahul&nbsp;<a href="/openid/appauth-android/pulls/assigned/tikurahul">tikurahul</a>

### CODE REVIEW

**Comment by iainmcgin** [comment]
+@williamdenniss and +@tikurahul for review

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/31#-:-KD6xtAzJ5cNg7uxCnEs:1341945597)*

**Comment by tikurahul** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/31)*

**Comment by tikurahul** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/31#-:-KD9_Zd-qXeHHgJ24xNm:1417088721)*

**Comment by WilliamDenniss** [comment]
Reviewed 10 of 10 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/31)*

**Comment by WilliamDenniss** [comment]
LGTM

**Pull request merged**
