### PR TITLE
Add HttpConnect wrapper for adding okHttp support

### PR DESCRIPTION
**Pull request by theScrabi**
If an app uses okHttp for every request it might be usefull for Appauth to also use okHttp.
This Pullrequest adds support for okHttp by adding a wrapper layer betwean HttpURLConnection and AppAuth.
Also it adds two implementations of this wrapper. One is plain HttpURLConnection, the other is based on okHttp. The goal of this commit is to be able to inject a custom `OkHttpClient` into the network requests made by AppAuth.

Now there are several things that need to be sort out before we can merge this.
1. Do we want the okHttp be part of AppAuth directly? This would mean that AppAuth will always have a dependency on the okHttp library. If we do not want this I could create an "AppAuth-Android:okHttp" library that can be included to any project as an additioin.
2. What is still required to be done to make this code well enough for this project?

#### TODO
- [ ] Write tests
- [ ] discuss weather OkHttp implementations should be part of this lib or not
- [ ] check if wrapper impl is ok
- [ ] update README.md

### CODE REVIEW

**Comment by judegpinto** [comment]
@theScrabi this is a really beneficial change, because it adds a lot more flexibility to the user, including being able to insert a non-SSLSocketfactory into the connection. this is an api breaking change, correct? is there a way we can implement this without breaking current functionality? or is the next release going to be api-breaking anyway?

**Comment by theScrabi** [comment]
I am sorry we decided not to follow this solution any more  so I will not be able to continue developing on this any more.

**Comment by agologan** [comment]
The library was designed around HttpURLConnection so it doesn't add any extra dependencies and force/suggest developers use one lib or another for their network stack.

There is however a way to replace the stack by using [ConnectionBuilder](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/connectivity/ConnectionBuilder.java)
In the past I've done this via OkHttp's OkUrlFactory which would create the requests.
While OkUrlFactory was removed you can still get it back via https://gist.github.com/swankjesse/dd91c0a8854e1559b00f5fc9c7bfae70 .

There is some value in being able to work with a variety of network libraries but that's all we have for now.

**Comment by svenjacobs** [comment]
It's very unfortunate to see that development for this has stalled / was cancelled 😢 

Being able to replace the internal HTTP framework for example with [OkHttp](https://square.github.io/okhttp/) would enable us to connect to services that only speak HTTP/2, which is more performant and secure.

**Comment by svenjacobs** [comment]
> The library was designed around HttpURLConnection so it doesn't add any extra dependencies and force/suggest developers use one lib or another for their network stack.

There are ways to design a library that no extra dependencies are forced onto the users.
For example there could be a `HttpClient` interface with a default implementation for `HttpURLConnection`. A separate artifact could then provide an implementation for OkHttp.

**Pull request closed without merging**
