### PR TITLE
Update Custom Tabs link

### PR DESCRIPTION
**Pull request by slang25**

### CODE REVIEW

**Comment by iainmcgin** [comment]
Thanks for this! Could you sign the OpenID Foundation CLA, and then I can merge this? You can add yourself to the CONTRIBUTORS file as part of this PR too.

**Comment by slang25** [comment]
Thanks @iainmcgin, I've filled out the CLA as requested 😃

**Comment by iainmcgin** [comment]
Sorry @slang25, I don't see you on [the list](https://openid.net/intellectual-property/contribution-license-agreement/) maintained by the OIDF - are you covered by one of the corporate agreements? If not, it may just be that the lawyers at the OIDF haven't updated the list yet, I'll check with them too.

**Comment by iainmcgin** [comment]
@slang25 I just reached out to the OIDF CLA admins, they say that they have not yet received a copy of the CLA from you. Could you please fill out either the individual or corporate CLA from [this page](https://openid.net/intellectual-property/contribution-license-agreement/) and email it to help@oidf.org?

**Comment by blundell** [comment]
Please re-open if you see this is still valid & you have correctly signed the CLA.

**Pull request closed without merging**
