### PR TITLE
Store OAuth related authorization exceptions on updates

### PR DESCRIPTION
**Pull request by iainmcgin**
Fix for #26.

---
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/38) &emsp; Multiple assignees:&emsp;@WilliamDenniss&nbsp;<a href="/openid/appauth-android/pulls/assigned/WilliamDenniss">WilliamDenniss</a>,&emsp;@tikurahul&nbsp;<a href="/openid/appauth-android/pulls/assigned/tikurahul">tikurahul</a>

### CODE REVIEW

**Comment by iainmcgin** [comment]
+@williamdenniss +@tikurahul for review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/38#-:-KDaQDI0dz1-9Fs0Lbo2:-219025510)*

**Comment by WilliamDenniss** [comment]
LGTM. +1 to storing the full exception.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/38#-:-KDfRuyhVe6tOwLzgjGK:641048713)*

**Comment by WilliamDenniss** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/38)*

**Comment by WilliamDenniss** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/38#-:-KDjFo2C6PTEuak385qs:1417088721)*

**Pull request merged**
