### PR TITLE
Dependency updates, gradle file cleanup and vector drawables

### PR DESCRIPTION
**Pull request by iainmcgin**
The gradle build files were getting pretty ugly, so this CL breaks them up into manageable, reusable chunks. While doing this, tool and library dependencies have been updated to the latest versions, enabling the use of vector drawables (to get rid of the various DPI versions of the icons used in the demo app). Finally, I switched from Picasso to Glide, which is the current recommended image loader library within Google.

---
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/95)

### CODE REVIEW

**Comment by iainmcgin** [comment]
+@tikurahul for review

---

Review status: 0 of 32 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/95#-:-KMeBWSdBEGOg2bdBxl9:-17244904)*

**Comment by tikurahul** [comment]
LGTM

---

Review status: 0 of 55 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/95#-:-KMzvMucwfOw3373V9SK:-492975247)*

**Comment by tikurahul** [comment]
Reviewed 33 of 36 files at r1, 26 of 27 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/95)*

**Comment by tikurahul** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/95#-:-KMzwA-JLtSL53dlJLws:1417088721)*

**Pull request merged**
