### PR TITLE
Add end session support

### PR DESCRIPTION
**Pull request by agologan**
Original-author: Sergiy Mokiyenko <smokiyenko@lohika.com>
See: https://github.com/openid/AppAuth-Android/pull/433

Needed the changes so I cleaned the original PR and applied existing patterns in order to match current code design.

### CODE REVIEW

**Comment by cratrifork** [comment]
Hey, I just tested this and it works perfectly! Thanks a bunch.

Only comment I have is that, when creating the EndSessionRequest, you assume that the user has an IdToken, I'm not really sure if this should be required. I our implementation towards KeyCloak I can send the AccessToken/RefreshToken instead. 

So I'm not really sure if it brings any value to the PR, but I just found it confusing that the parameter was called idToken.

**Comment by agologan** [comment]
@cratrifork Per https://openid.net/specs/openid-connect-session-1_0.html#RPLogout the paramater should be the previously issued ID token. 
Different vendors may support other hints as this parameter but the purpose here is not create a KeyCloak-specific implementation.

**Comment by srajkovic** [comment]
Any chance this might get reviewed and merged? We'd love to have this functionality since we're having issues with getting our logout flow to respect the App Link we have registered and go back to our app, and it's probably due to the hacky workarounds. Tagging @iainmcgin since it seems like you're a current maintainer. Happy to help if I can in some way.

**Comment by wassimsalib** [comment]
Any updates on this PR? we are currently in the same situation and this PR will solve out problems too.

**Comment by agologan** [comment]
Updated this PR integrating the latest changes.

_Since there is enough interest in this PR I have published a binary to use:_ https://bintray.com/agologan/com.agologan/appauth/0.7.1-14-ged7e194

**Comment by chrisbanes** [comment]
FYI: this added an API breaking change (removing the 3 arg constructor from `AuthorizationServiceConfiguration`).

**Comment by agologan** [comment]
> FYI: this added an API breaking change (removing the 3 arg constructor from `AuthorizationServiceConfiguration`).

Fixed backwards compatibility issue in #636 . Thank you.

**Pull request merged**
