### PR TITLE
Move token request URI generation into TokenRequest

### PR DESCRIPTION
**Pull request by iainmcgin**
After this, we can remove all parameter related code from AuthorizationService.

[Review on Reviewable](https://reviewable.io/reviews/openid/appauth-android/2)

### CODE REVIEW

**Comment by iainmcgin** [comment]
+@WilliamDenniss for review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/2#-:-KBWvqwxfS8zWdDfagdr:2061413712)*

**Comment by tikurahul** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/2)*

**Comment by tikurahul** [comment]
LGTM

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openid/appauth-android/2#-:-KBY3HoCCfwGTVUICMHX:676834233)*

**Review by teddydesk — APPROVED** [review]

**Review by QQn00bs — CHANGES_REQUESTED** [review]
- [ ] Q

**Pull request merged**
