### PR TITLE
Permit 2016 as a copyright year

### PR DESCRIPTION
**Pull request by iainmcgin**
This change is [Reviewable](https://reviewable.io/reviews/openid/appauth-android/48)

### CODE REVIEW

**Comment by iainmcgin** [comment]
+@williamdenniss for review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/48#-:-KFzTjvHpSh01if7noFu:-1826320048)*

**Comment by WilliamDenniss** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[config/checkstyle/java.header, line 2 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/48#-KFzgIHYzTfZM0ayfXtn:-KFzgIHZ17_FO_7db4d-:373862116) ([raw file](https://github.com/openid/appauth-android/blob/876857ae79e6669b600332540111a180f0b0e681/config/checkstyle/java.header#L2)):*
What about: 20[0-9]{2}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/48)*

**Comment by WilliamDenniss** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/48#-:-KFzh-DJGhU1YSkvml4D:1417088721)*

**Comment by iainmcgin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[config/checkstyle/java.header, line 2 \[r1\]](https://reviewable.io:443/reviews/openid/appauth-android/48#-KFzgIHYzTfZM0ayfXtn:-KFzhl6fvjSYZyWpTOHL:-499146009) ([raw file](https://github.com/openid/appauth-android/blob/876857ae79e6669b600332540111a180f0b0e681/config/checkstyle/java.header#L2)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openid/appauth-android/48)*

**Pull request merged**
